name: Simple Flutter Workflow

on:
  push:
    branches:
      - main

jobs:
  automation:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Workflow Success
      run: echo "GitHub Actions executed successfully"
